Models/Curso.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;


namespace platzi_asp_net_core.Models
{
    public class Curso:ObjetoEscuelaBase
    {
        [Required]
        public override string Nombre { get; set; }
        public TiposJornada Jornada { get; set; }
        public List<Asignatura> Asignaturas{ get; set; }
        public List<Alumno> Alumnos{ get; set; }

        public string Dirección { get; set; }
        
        public string EscuelaId { get; set; }
        
        public Escuela Escuela { get; set; }
    }
}

Controllers/CursoController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using platzi_asp_net_core.Models;
using System.Linq;

namespace platzi_asp_net_core.Controllers
{
    public class CursoController : Controller
    {
        [Route("Curso/Index")]
        [Route("Curso/{cursoId?}")]
        [Route("Curso/Index/{cursoId?}")]
        public IActionResult Index(string cursoId)
        {
            
            if (!string.IsNullOrWhiteSpace(cursoId))
            {
                Curso curso = (from cur in _context.Cursos where cur.Id == cursoId select cur)
                    .SingleOrDefault();

                if (curso!=null)
                {
                    return View("Index",curso);    
                }
                
            }
            IEnumerable<Curso> listCurso = _context.Cursos;
            return View("MultiCurso", listCurso);
            
        }

        public IActionResult MultiCurso()
        {
            IEnumerable<Curso> listCurso = _context.Cursos;

            return View("MultiCurso", listCurso);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Curso curso)
        {
            if (!ModelState.IsValid)
            {
                return View(curso);
            }
            Escuela escuela = _context.Escuelas.FirstOrDefault();
            
            curso.Id = Guid.NewGuid().ToString();
            curso.EscuelaId = escuela.Id;
            _context.Cursos.Add(curso);
            _context.SaveChanges();
            return View("index",curso);
        }
        
        public IActionResult Edit(Curso curso)
        {
            return View("Edit",curso);
        }
        
        [HttpPost]
        public IActionResult Update(Curso curso,string CursoId)
        {
            if (!ModelState.IsValid)
            {
                return View("Edit",curso);
            }
            Escuela escuela = _context.Escuelas.FirstOrDefault();
            
            
            
            curso.EscuelaId = escuela.Id;
            _context.Cursos.Update(curso);
            _context.SaveChanges();
            return MultiCurso();
        }

        public IActionResult Delete(Curso curso)
        {
            
            _context.Cursos.Remove(curso);
            _context.SaveChanges();
            return MultiCurso();
        }
        
        private EscuelaContext _context;
        public CursoController(EscuelaContext context)
        {
            _context = context;
        }
    }
}

Views/Curso/Create.cshtml
@model Curso

@{
    ViewData["Title"] = "Creación de Curso";
    Layout = "Simple";
}

<h1>@ViewData["Title"]</h1>

<div asp-validation-summary="All"></div>
<form method="POST">
    <div>
        <label asp-for="Nombre"></label>
        <input asp-for="Nombre"/>
    </div>
    <div>
        <label asp-for="Dirección"></label>
        <input asp-for="Dirección"/>
    </div>
    <div>
            <label asp-for="Jornada"></label>
        @* <input asp-for="Jornada"/> *@
        @Html.DropDownList(
            "Jornada",
            Html.GetEnumSelectList<TiposJornada>(),
            "Seleccione una jornada",
            new {@class="form-control"}
            )
        </div>
    <input type="submit"/>
</form>

Views/Curso/Edit.cshtml
@model Curso

@{
    ViewData["Title"] = "Edición de Curso";
    Layout = "Simple";
}

<h1>@ViewData["Title"]</h1>

<div asp-validation-summary="All"></div>
<form method="POST" asp-controller="Curso" asp-action="Update">
    <div>
        <label asp-for="Nombre"></label>
        <input asp-for="Nombre"/>
    </div>
    <div>
        <label asp-for="Dirección"></label>
        <input asp-for="Dirección"/>
    </div>
    <div>
        <label asp-for="Jornada"></label>
        @* <input asp-for="Jornada"/> *@
        @Html.DropDownList(
            "Jornada",
            Html.GetEnumSelectList<TiposJornada>(),
            "Seleccione una jornada",
            new { @class = "form-control" }
            )
    </div>
    <input type="hidden" asp-for="Id" />

    <input type="submit"/>
</form>

Views/Curso/Index.cshtml
@model Curso

@{
    ViewData["Title"] = "Información Curso";
    Layout = "Simple";
}

<h1>@ViewData["Title"]</h1>

<strong>Desde la vista normal</strong>
<p>
    Nombre: @Model.Nombre <br/>
    Id:@Model.Id  
</p>

<strong>Desde la vista parcial</strong>
<partial name="ObjectoEscuelaSimple"/>

<p><i>@ViewBag.Fecha</i></p>

Views/Curso/MultiCurso.cshtml
@model IEnumerable<Curso>

@{
    ViewData["Title"] = "Información Curso";
    Layout = "Simple";
}

<h1>@ViewData["Title"]</h1>

<strong>Desde la vista parcial</strong><br/><br/>
<button type="button" class="btn btn-secondary">Agregar</button><br/>    
<table class="table table-dark">
    <thead>
    <tr>
        <th scope="col">Id</th>
        <th scope="col">Nombre</th>
        <th scope="col">Editar</th>
        <th scope="col">Eliminar</th>
    </tr>
    </thead>
    <tbody>
    
        @foreach (Curso curso in @Model)
        {
            
            <tr>
               
                <td>@curso.Id</td>
                <td>@curso.Nombre</td>
                <td>
                    <button type="button" class="btn btn-warning" onclick="location.href='@Url.Action("Edit","Curso",curso)'">Edit</button>    
                </td>
                <td>
                    <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("Delete","Curso",curso)'">Delete</button>
                </td>
                
            </tr>
           
        }
    </tbody>
</table>
@* <table class="table table-dark table-hover"> *@
@*     <thead> *@
@*     <tr> *@
@*         <th scope="col">Id</th> *@
@*         <th scope="col">Nombre</th> *@
@*     </tr> *@
@*     </thead> *@
@*     <tbody> *@
@*     @foreach (Curso curso in @Model) *@
@*     { *@
@*         <tr> *@
@*             <td>@curso.Nombre</td> *@
@*             <td>@curso.Id</td> *@
@*              *@
@*         </tr> *@
@*     } *@
@*     </tbody> *@
@* </table> *@